/*ALIAS*/
/*NESTED SELECT*/

SELECT DISTINCT(CITY) FROM 
(SELECT CITY FROM STATION 
 WHERE CITY LIKE 'A%' 
 OR CITY LIKE 'E%' 
 OR CITY LIKE 'I%' 
 OR CITY LIKE 'O%' 
 OR CITY LIKE 'U%') C
 
 WHERE CITY LIKE '%A' 
 OR CITY LIKE '%E' 
 OR CITY LIKE '%I' 
 OR CITY LIKE '%O' 
 OR CITY LIKE '%U'

--OR

SELECT DISTINCT(CITY) FROM STATION
WHERE CITY REGEXP '^[AEIOU].*[AEIOU]$'
